name: Core Release
run-name: Update helm chart for core release ${{ inputs.tag }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Core tag"
        required: true
        default: dev
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Changeset and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Configure Git
        run: |
          git config user.name openprojectci
          git config user.email operations+openprojectci@openproject.com

      - name: Bump release
        run: ruby bin/update_from_core_release "${{ inputs.tag }}"
